name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Build avec Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Envoyer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartBatteryAI-APK
          path: bin/*.apk
